apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  lables:
    type: hostpath
    environment: dev
spec:
  storageClassName: hostpath 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"