apiVersion: v1
kind: Deployment 
metadata:
  name: jenkinds-master
  lables:
    app: cicd-master
    environment: production
spec:
  selector:
    matchLabels:
      app: cicd-master
      environment: production
  template:
    metadata:
      name: jenkinds-master
      lables: 
        app: cicd-master
        environment: production
    spec:
      containers:
      - name: cicd-master
        image: jenkins/jenkins:lts
        ports:
          - name: cicd-port
            containerPort: 80
            protocol: TCP
        volumeMount:
          - name: jenkins-data
            mountPath: /var/jenkins_home #/var/lib/jenkins
      volumes:
       - name: jenkins-data
         PersistentVolumeClaim:
          claimName: jenkins-pvc


