apiVersion: v1
kind: PersistentVolume 
metadata:
  name: jenkins-pv
  labels:
    app: jenkins-pv
    environment: dev 
spec:
  storageClassName: nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.31.35.230
    path: /var/nfs/jekins-data